#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f cpu.vcd


#run Verilator to translate Verilog into C++, including the C++ testbench
verilator -Wall --cc --trace ALU.sv --exe cpu_tb.cpp
verilator -Wall --cc --trace ALUMux.sv --exe cpu_tb.cpp
verilator -Wall --cc --trace control_unit.sv --exe cpu_tb.cpp
verilator -Wall --cc --trace cpu.sv --exe cpu_tb.cpp
verilator -Wall --cc --trace decode_instr.sv --exe cpu_tb.cpp
verilator -Wall --cc --trace instr_mem.sv --exe cpu_tb.cpp
verilator -Wall --cc --trace ProgramCounter.sv --exe cpu_tb.cpp
verilator -Wall --cc --trace regFile.sv --exe cpu_tb.cpp
verilator -Wall --cc --trace sign_extend.sv --exe cpu_tb.cpp

#build C++ project via make automatically generated by verilator
make -j -C obj_dir/ -f Vcpu.mk Vcpu

#clears up all the compile time junk
#if youre having problems and need to see the errors comment the clear
#clear

#run executable simulation file
obj_dir/Vcpu