#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f ProgramCounter.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace ProgramCounter.sv --exe ProgramCounter_tb.cpp

# build C++ project via make automatically generated by Verilator

make -j -C obj_dir/ -f VProgramCounter.mk VProgramCounter

# run executable simulation file
obj_dir/VProgramCounter
